development:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"]  %>
  secret_key_base: f08aef5a054f9d0c80a8f65685b848978db0842a313efb92c146c1293fd1dab9dfdc84d8c47d18856a67efacfec497375a9ef8c79858f7603e6506d7e4a663a2

production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"]  %>
  secret_key_base: <%= ENV["OMNIAUTH_SECRET_KEY_BASE"]  %> 
